# CD Pipeline for MvcMovie
trigger: none

resources:
  pipelines:
  - pipeline: ci_pipeline
    source: 'MvcMovie-CI'
    trigger:
      branches:
      - main

pool:
  name: 'Default' # The orchestrator

jobs:
- deployment: DeployWeb
  displayName: 'Deploy to Local Machine'
  # This "environment" targets the agent you registered with your script
  environment: 
    name: 'MvcMovieDeploymentGroup' 
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - download: ci_pipeline
          artifact: drop

        - task: ExtractFiles@1
          inputs:
            archiveFilePatterns: '$(Pipeline.Workspace)/ci_pipeline/drop/*.zip'
            destinationFolder: 'C:\MvcMovieDeploy'
            cleanDestinationFolder: true
